CI:cx2

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,7 +13,7 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Set up JDK 17
         uses: actions/setup-java@v3
@@ -43,17 +43,15 @@ jobs:
           disable-animations: true
           script: |
             adb wait-for-device
-            adb shell settings put global window_animation_scale 0 &
-            adb shell settings put global transition_animation_scale 0 &
-            adb shell settings put global animator_duration_scale 0 &
-            echo "Esperando al emulador..."
-            sleep 90 
-            echo "Iniciando pruebas..."
-            ./gradlew connectedDebugAndroidTest || echo "Android tests failed, but continuing pipeline..."
+            adb shell settings put global window_animation_scale 0
+            adb shell settings put global transition_animation_scale 0
+            adb shell settings put global animator_duration_scale 0
+            sleep 90
+            ./gradlew connectedDebugAndroidTest || echo "Android tests failed, continuing pipeline..."
 
       - name: Upload Android Test Report
         if: always()
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: android-test-report
           path: app/build/reports/androidTests/connected/
